### ISSUE TITLE
patters.map is not a function

### ISSUE THREAD

**Issue by samir-kamble** [becompany/angular2-rss-reader-tutorial#3]
```
patterns.map is not a function
TypeError: patterns.map is not a function
    at GlobCopyWebpackPlugin.apply (C:\Users\Admin.admin-PC\Desktop\test\node_mo
dules\angular-cli\plugins\glob-copy-webpack-plugin.js:16:29)
    at Compiler.apply (C:\Users\Admin.admin-PC\Desktop\test\node_modules\tapable
\lib\Tapable.js:270:16)
    at WebpackOptionsApply.process (C:\Users\Admin.admin-PC\Desktop\test\node_mo
dules\webpack\lib\WebpackOptionsApply.js:59:18)
    at webpack (C:\Users\Admin.admin-PC\Desktop\test\node_modules\webpack\lib\we
bpack.js:28:48)
    at Class.run (C:\Users\Admin.admin-PC\Desktop\test\node_modules\angular-cli\
tasks\serve-webpack.js:38:27)
    at C:\Users\Admin.admin-PC\Desktop\test\node_modules\angular-cli\commands\se
rve.js:108:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Application is not starting giving above error.

**Comment by jpuerto** [comment]
Could you provide information about your environment and steps to reproduce?
 I've just clone the repository and it works fine.

```
> git clone https://github.com/becompany/angular2-rss-reader-tutorial.git
> cd angular2-rss-reader-tutorial/
> git checkout cordova-device-plugin
> npm install
> cd cordova
> cordova platform add browser
> cordova run browser
```

**Comment by samir-kamble** [comment]
i guess i missed cordova device plugin let me try once more

**Comment by samir-kamble** [comment]
Error still persists at cordova platform add. My environment as follows,

``NodeJS : v7.3.0
cordova : 6.4.0
npm : 3.10.10
git :git version 2.11.0.windows.1 ``

Please let me know any further info needed.

**Comment by jpuerto** [comment]
Unfortunately I'm using Linux based OS to build the project so I did not test with Windows, anyway in the blog post there's people that seems to use Windows without problems. The only difference in my setup besides the Linux OS is the NodeJS version that I'm using the LTS and not the version 7.x.

Could you try the following?

* Create a simple Apache Cordova project and build. Does it works?
* Try to build the Angular project without the Apache Cordova support. Does it works? 
* Lower the version of NodeJS to the LTS version and try again.

The error seems to be in the `ng` tool while building the Angular 2 project.

**Comment by samir-kamble** [comment]
Create a simple Apache Cordova project and build. Does it works?
This works

Try to build the Angular project without the Apache Cordova support. Does it works?
This works too

Lower the version of NodeJS to the LTS version and try again.
Need to test it.

**Comment by jpuerto** [comment]
It should work now with latest version of NodeJS. I'm not able to reproduce the issue.
