### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by ShanmugapriyaDurairaj** [becompany/angular2-rss-reader-tutorial#7]
error syscall open
15 error enoent ENOENT: no such file or directory, open 'D:\trainning\a2-to-cordova\angular2-rss-reader-tutorial-cordova-integration\cordova\www\package.json'
16 error enoent ENOENT: no such file or directory, open 'D:\trainning\a2-to-cordova\angular2-rss-reader-tutorial-cordova-integration\cordova\www\package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.

**Comment by jpuerto** [comment]
Not reproducible. Please elaborate the description and reopen in case that it is still necessary.
